version: "3.8"

services:
  app:
    build:
      context: ./
      target: prod
    ports:
      - 8081:8081
    expose:
      - 8081

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf